"""add product_report table

Revision ID: 2a089473c142
Revises: a3c9f1d2e845
Create Date: 2026-05-22 19:40:03.582280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '2a089473c142'
down_revision: Union[str, None] = 'a3c9f1d2e845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_status'), table_name='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_status'), 'product', ['status'], unique=False)
    # ### end Alembic commands ###
