spring.application.name=c2c-market

# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/c2c_market
spring.datasource.username=postgres
spring.datasource.password=Pepe2112
spring.jpa.hibernate.ddl-auto=validate
# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Configuración de Mail para el NotificationService
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[EMAIL_ADDRESS]
spring.mail.password=[PASSWORD]
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=admin
spring.security.user.password=admin

#entrar a la base de datos: sudo -u postgres psql -d c2c_market  
# ver las tablas \dt